"""initial schema

Revision ID: 69f716fc5635
Revises: 
Create Date: 2026-08-13 07:03:20.513456
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# Custom column types are rendered by autogenerate as fully-qualified names
# (e.g. app.db.types.GUID), so the module has to be importable here.
import app.db.types


revision = '69f716fc5635'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action', sa.String(length=96), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_index('ix_audit_ws_time', 'audit_logs', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('alerts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('natural_language', sa.Text(), nullable=False),
    sa.Column('rule', sa.JSON(), nullable=False),
    sa.Column('metric_key', sa.String(length=96), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_workspace_id'), 'alerts', ['workspace_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('connection_meta', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.String(length=24), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_workspace_id'), 'data_sources', ['workspace_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('metric_key', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('parent_id', app.db.types.GUID(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['investigations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_reference'), 'investigations', ['reference'], unique=True)
    op.create_index(op.f('ix_investigations_workspace_id'), 'investigations', ['workspace_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'workspace_id', name='uq_member')
    )
    op.create_table('metrics',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('key', sa.String(length=96), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('aggregation', sa.String(length=32), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('base_table', sa.String(length=200), nullable=False),
    sa.Column('date_column', sa.String(length=200), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('approved_by', sa.String(length=320), nullable=True),
    sa.Column('approved_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', 'version', name='uq_metric_ver')
    )
    op.create_index(op.f('ix_metrics_workspace_id'), 'metrics', ['workspace_id'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('task_type', sa.String(length=48), nullable=False),
    sa.Column('algorithm', sa.String(length=96), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('feature_names', sa.JSON(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_workspace_id'), 'ml_models', ['workspace_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_table('agent_runs',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('investigation_id', app.db.types.GUID(), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_investigation_id'), 'agent_runs', ['investigation_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('workspace_id', app.db.types.GUID(), nullable=False),
    sa.Column('data_source_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('physical_table', sa.String(length=200), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('freshness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_workspace_id'), 'datasets', ['workspace_id'], unique=False)
    op.create_table('dataset_columns',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('dataset_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=64), nullable=False),
    sa.Column('inferred_role', sa.String(length=32), nullable=False),
    sa.Column('null_pct', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_columns_dataset_id'), 'dataset_columns', ['dataset_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('agent_run_id', app.db.types.GUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=96), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('latency_ms', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_calls_agent_run_id'), 'tool_calls', ['agent_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_calls_agent_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_dataset_columns_dataset_id'), table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index(op.f('ix_datasets_workspace_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_agent_runs_investigation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_ml_models_workspace_id'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_metrics_workspace_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_investigations_workspace_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_reference'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_data_sources_workspace_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_alerts_workspace_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_audit_ws_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
