"""
Report export (spec section 47).

An investigation that cannot leave the tool does not reach the meeting where the
decision gets made. Export exists so the reasoning travels with the number.

The rule the format follows: **nothing is exported without its qualifiers.**
A confidence score always carries its limiting factor, a driver always carries
its contribution, a causal estimate always carries its diagnostics, and a
recommendation always carries the assumption behind its expected impact. It is
easy to build an export that renders only the headline, and that export is
actively harmful — it strips exactly the parts that tell a reader how much
weight the number can bear.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO

log = logging.getLogger(__name__)

CONFIDENCE_BANDS = ((0.75, "high"), (0.5, "moderate"), (0.35, "low"))


@dataclass(slots=True)
class Report:
    reference: str
    question: str
    markdown: str

    @property
    def filename(self) -> str:
        return f"{self.reference or 'investigation'}.md"


def _pct(value, digits: int = 1) -> str:
    try:
        return f"{float(value) * 100:.{digits}f}%"
    except (TypeError, ValueError):
        return "—"


def _band(score: float) -> str:
    for floor, label in CONFIDENCE_BANDS:
        if score >= floor:
            return label
    return "insufficient"


def build_markdown(investigation: dict) -> str:
    """Render a stored investigation. Takes the API shape, so an exported report
    and an on-screen one cannot drift apart."""
    reference = investigation.get("reference", "")
    question = investigation.get("question", "(no question recorded)")
    lines: list[str] = [
        f"# {question}",
        "",
        f"`{reference}` · generated {datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}",
        "",
    ]

    headline = investigation.get("headline")
    if headline:
        lines += [f"**{headline}**", ""]

    # --- confidence, never without its limiting factor ---
    confidence = investigation.get("confidence") or {}
    if confidence.get("overall") is not None:
        overall = float(confidence["overall"])
        limiting = confidence.get("limiting_factor", "unknown")
        lines += [
            "## Confidence",
            "",
            f"**{_pct(overall, 0)} ({_band(overall)})** — limited by *{limiting}*.",
            "",
            "| Component | Score |",
            "| --- | ---: |",
        ]
        for name in ("data", "statistical", "model", "reasoning"):
            if name in confidence:
                lines.append(f"| {name.title()} | {_pct(confidence[name], 0)} |")
        lines += ["", _confidence_caveat(overall, limiting), ""]

    narrative = investigation.get("narrative")
    if narrative:
        lines += ["## What happened", "", str(narrative).strip(), ""]

    lines += _drivers_section(investigation)
    lines += _causal_section(investigation)
    lines += _recommendations_section(investigation)
    lines += _evidence_section(investigation)

    verdict = investigation.get("verdict")
    if verdict:
        lines += [
            "## Verification",
            "",
            ("Every figure in this report was matched against a computed value "
             "before the report was written."
             if verdict == "approved" else
             "**This report was flagged by the verification step.** At least one "
             "claim in the narrative could not be matched to a computed value. "
             "Treat the numbers as unverified."),
            "",
        ]

    lines += [
        "---",
        "",
        "*Generated by InsightOS. Figures are computed in Python; the narrative "
        "is checked against them before release. Assumptions and caveats above "
        "are part of the result, not boilerplate.*",
    ]
    return "\n".join(lines)


def _confidence_caveat(overall: float, limiting: str) -> str:
    if overall >= 0.75:
        return ("The evidence supports acting on this, subject to the caveats "
                "below.")
    explanations = {
        "statistical": ("The aggregate change is within what normal variation "
                        "produces, even where individual segments moved sharply. "
                        "Segment-level findings may still be real; the headline "
                        "is not established."),
        "data": ("Data quality limits this result — missing values, duplicates "
                 "or freshness problems in the underlying rows."),
        "model": ("The forecast or attribution model fits this series poorly, so "
                  "its projections carry wide error."),
        "reasoning": ("The chain from evidence to conclusion has a weak link; "
                      "read the evidence section before relying on it."),
    }
    return ("**Directional only.** "
            + explanations.get(limiting,
                               "Confidence is below the threshold for acting on "
                               "this result alone."))


def _drivers_section(investigation: dict) -> list[str]:
    drivers = (investigation.get("evidence", {}) or {}).get("root_cause", {})
    drivers = drivers.get("drivers") if isinstance(drivers, dict) else None
    drivers = drivers or investigation.get("drivers") or []
    if not drivers:
        return []
    lines = ["## What moved", "",
             "| Dimension | Segment | Contribution | Within-segment change |",
             "| --- | --- | ---: | ---: |"]
    for driver in drivers[:10]:
        lines.append(
            f"| {driver.get('dimension', '—')} | {driver.get('segment', '—')} | "
            f"{_pct(driver.get('contribution_pct'), 2)} | "
            f"{_pct(driver.get('change_pct'), 1)} |")
    lines += ["",
              "*Contribution is each segment's share of the total change and sums "
              "to it exactly. Within-segment change is that segment's own "
              "movement — a large percentage on a small segment moves the total "
              "very little.*",
              ""]
    return lines


def _causal_section(investigation: dict) -> list[str]:
    estimate = (investigation.get("evidence", {}) or {}).get("causal")
    if not isinstance(estimate, dict):
        return []
    lines = ["## Causal estimate", ""]
    if not estimate.get("credible", False):
        failed = [d["name"] for d in estimate.get("diagnostics", [])
                  if not d.get("passed")]
        lines += [
            "**Withheld.** This estimate did not pass "
            + ", ".join(failed or ["its diagnostics"])
            + ", so the difference in the data cannot be attributed to the "
              "intervention here.",
            ""]
        return lines
    lines += [f"{estimate.get('interpretation', '')}", ""]
    if estimate.get("caveats"):
        lines += ["**This assumes:**", ""]
        lines += [f"- {c}" for c in estimate["caveats"]]
        lines.append("")
    return lines


def _recommendations_section(investigation: dict) -> list[str]:
    recommendations = investigation.get("recommendations") or []
    if not recommendations:
        return []
    lines = ["## Recommended next steps", ""]
    for index, item in enumerate(recommendations, start=1):
        action = item.get("action") or item.get("title") or "(unnamed action)"
        lines.append(f"{index}. **{action}**")
        if item.get("rationale"):
            lines.append(f"   {item['rationale']}")
        impact = item.get("expected_impact")
        if impact is not None:
            # The assumption travels with the number, always. An expected impact
            # without its basis reads as a forecast rather than as arithmetic on
            # a stated recovery rate.
            basis = item.get("impact_basis") or (
                "assumes the affected segment recovers halfway to its "
                "pre-decline level; it is arithmetic on that assumption, not a "
                "prediction")
            lines.append(f"   *Expected impact: {impact} — {basis}.*")
        lines.append("")
    return lines


def _evidence_section(investigation: dict) -> list[str]:
    evidence = investigation.get("evidence") or {}
    if not evidence:
        return []
    lines = ["## Evidence", ""]
    sql = evidence.get("sql")
    if sql:
        lines += ["The query behind these figures:", "", "```sql", str(sql).strip(),
                  "```", ""]
    metric = evidence.get("metric")
    if isinstance(metric, dict):
        lines += ["| | Value |", "| --- | ---: |"]
        for label, key in (("Current period", "current"),
                           ("Comparison period", "previous")):
            if metric.get(key) is not None:
                lines.append(f"| {label} | {float(metric[key]):,.2f} |")
        if metric.get("change_pct") is not None:
            lines.append(f"| Change | {_pct(metric['change_pct'], 2)} |")
        lines.append("")
    significance = evidence.get("significance")
    if isinstance(significance, dict) and significance.get("p_value") is not None:
        verdict = ("statistically significant"
                   if significance.get("significant") else
                   "within normal variation")
        lines += [f"Significance: p = {float(significance['p_value']):.4f} "
                  f"({verdict}).", ""]
    return lines


def to_pdf(markdown_text: str, title: str = "InsightOS report") -> bytes:
    """Render to PDF.

    Deliberately plain: headings, paragraphs, code blocks and list items. Tables
    become preformatted text rather than being silently dropped, because a
    missing table in an exported report is worse than an ugly one.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Preformatted, Spacer

    styles = getSampleStyleSheet()
    mono = ParagraphStyle("mono", parent=styles["Code"], fontSize=7.5, leading=9.5)
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer, pagesize=A4, title=title,
        leftMargin=20 * mm, rightMargin=20 * mm,
        topMargin=18 * mm, bottomMargin=18 * mm)

    flow: list = []
    in_code = False
    code_buffer: list[str] = []
    table_buffer: list[str] = []

    def flush_table() -> None:
        if table_buffer:
            flow.append(Preformatted("\n".join(table_buffer), mono))
            flow.append(Spacer(1, 5))
            table_buffer.clear()

    for raw in markdown_text.splitlines():
        line = raw.rstrip()
        if line.startswith("```"):
            if in_code:
                flow.append(Preformatted("\n".join(code_buffer), mono))
                flow.append(Spacer(1, 6))
                code_buffer.clear()
            in_code = not in_code
            continue
        if in_code:
            code_buffer.append(line)
            continue
        if line.startswith("|"):
            table_buffer.append(line)
            continue
        flush_table()

        if not line:
            flow.append(Spacer(1, 5))
        elif line.startswith("### "):
            flow.append(Paragraph(_escape(line[4:]), styles["Heading3"]))
        elif line.startswith("## "):
            flow.append(Paragraph(_escape(line[3:]), styles["Heading2"]))
        elif line.startswith("# "):
            flow.append(Paragraph(_escape(line[2:]), styles["Title"]))
        elif line.startswith("---"):
            flow.append(Spacer(1, 10))
        else:
            flow.append(Paragraph(_inline(line), styles["BodyText"]))

    flush_table()
    if code_buffer:
        flow.append(Preformatted("\n".join(code_buffer), mono))

    document.build(flow)
    return buffer.getvalue()


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _inline(text: str) -> str:
    """Convert the small subset of Markdown the reports use into ReportLab tags."""
    import re

    escaped = _escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escaped)
    escaped = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<i>\1</i>", escaped)
    escaped = re.sub(r"`([^`]+?)`", r"<font face='Courier'>\1</font>", escaped)
    return escaped


def build_report(investigation: dict) -> Report:
    return Report(reference=investigation.get("reference", ""),
                  question=investigation.get("question", ""),
                  markdown=build_markdown(investigation))
